### ISSUE TITLE
International Clay

### ISSUE THREAD

**Issue by YauronBis** [bleroy/clay#2]
(French translate below)

Hello. I congratulate you on this wonderful work. I've been trying to reach you since 2 days: FaceBook, Skype because I'm not proficient enough on GitHub to make myself a PullRequest according to my suggestion:
Having worked on BIM, with the opensource xBIM library, I realized that as part of the project that was mine, I needed to manipulate polymorphic objects whose description had to be external to the code. So I realized a MetaModel database that includes the entire IFC language (grammar, structural relationships, types), indexing objects and their attributes. By doing so, with this referential, I could store the IFC data in a relational format, and thus scalar, requérable, etc ... Having backed a flow of translation indexed on a language code (FR, UK, ...), I could thus ask that the attributes like the objects translate instantly into natural language. Alas I was not aware of the existence of the Clay project, and I did not have time to upgrade to DynanicObject. So I did it my way.
Today I take notice of your work! And I wonder if it would not be appropriate to offer additional services: external feed by metamodel, linguistic flow, translation flow.
Perspectives are important, as this could lead to the creation of shared object libraries in the form of a database shared in clouding, trans-cultural, and therefore international.
It would be best to talk about it vocally, I think.

--/--

Bonjour. Je vous félicite pour ce travail admirable. Je cherche à vous joindre depuis 2 jours : FaceBook, Skype car je ne suis pas suffisamment compétent sur GitHub pour effectuer pr moi même un PullRequest conforme à ma suggestion : 
Ayant travaillé sur le BIM, avec la librairie opensource xBIM, je me suis rendu compte que dans le cadre du projet qui était le mien, j'avais besoin de manipuler des objets polymorphes dont la description devaient être externe au code. J'ai donc réalisé une base de données MetaModèle reprenant l'intégralité du langage IFC (grammaire, relations structurelles, types), indexant les objets et leurs attributs. Ce faisant, avec ce référentielle, je pouvais stocker les données IFC dans un format relationnel, et donc scalaire, requérable, etc... Ayant adossé un flux de traduction indexé sur un code linguistique (FR, UK, ...), je pouvais ainsi demander que les attributs comme les objets se traduisent instantanément en langage naturel. Hélas je n'étais pas au courant de l'existence du projet Clay, et je n'avais pas le temps de monter en compétence sur DynanicObject. J'ai donc fait à ma façon.
Aujourd'hui je prends connaissance de votre travail ! Et je me demande si il ne serait pas opportun de proposer des services supplémentaires : alimentation externe par métamodèle, flux linguistique, flux de traduction. 
Les perspectives sont importante, car cela pourrait aboutir à la création de bibliothèques objets partagées sous la forme de base de données partagées en clouding, trans-culturelle, donc internationale.
Le mieux serait d'en parler vocalement je pense.

**Comment by bleroy** [comment]
Looks like this could be implemented as a new behavior. If so, you shouldn't need to modify Clay, but just add your own behavior to it.

**Comment by YauronBis** [comment]
(French translate below)

I was willing to provide you with an important part of my work so that together but on your behalf, we could develop an international standart, metamodel repository supporting multiple translations. I thought this challenge will stimulate you.

--/--

J'étais disposé à vous fournir une part importante de mon travail pour qu'ensemble mais en votre nom, nous puissions mettre au point un standart international, de référentiel metamodèle supportant les traductions multiples. Je pensais que ce challenge vous stimulerai.

**Comment by bleroy** [comment]
I'm sorry, I'm happy to take contributions, and to answer questions, but I don't have enough time to take new projects. I'm already involved in more open-source efforts than I can possibly deliver on. It would not be fair to you or to contributors and users of my other projects to promise involvement. I sincerely wish you good luck.
