### ISSUE TITLE
Deleting properties

### ISSUE THREAD

**Issue by jprinsloo** [bleroy/clay#3]
Hi bleroy,

Thank you for this amazing library.

I just want to know how one should delete properties that were dynamically added to a clay object?

Example:

`New = new ClayFactory();`
`Node = New.Node();`
`Node.property = "property";`

How can I remove the "property" from the dynamic object?

**Comment by bleroy** [comment]
There's nothing specific in place, although it would be fairly easy to update the interface to support it. It should be functionally equivalent however to just set the property to null.
